export {default as getAutomatedReadability} from './automated-readability-index';
export {default as getAverageGradeLevel} from './average-grade-level';
export {default as getCharacterCount} from './character-count';
export {default as getColemanLiau} from './coleman-liau-index';
export {default as getFleschKincaidIndex} from './flesch-kincaid-index';
export {default as getFleschReadabilityIndex} from './flesch-readability-index';
export {default as getLongSentenceCount} from './long-sentences-count';
export {default as getParagraphCount} from './paragraph-count';
export {default as getPolysyllables} from './polysyllables';
export {default as getReadingTime} from './reading-time';
export {default as getSentenceCount} from './sentence-count';
export {default as getSentiment} from 'sentiment';
export {default as getSmogIndex} from './smog-index';
export {default as getSyllableCount} from 'syllable';
export {default as getTotalCharacterCount} from './total-character-count';
export {default as getWithoutSpacesCharacterCount} from './without-spaces-character-count';
export {default as getWordCount} from './word-count';
// export {default as getWordOccurenceCount} from 'word-occurence-count';
